
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/componenets/navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UniteUp',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={'inter.className bg-gray-300'}>
      <Navbar />
      
        {children}</body>
    </html>
  )
}
